# Generated by Django 4.0.1 on 2022-01-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='https://i.imgur.com/z7fPkB9.png', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='John Davies', max_length=100),
            preserve_default=False,
        ),
    ]
