# Generated by Django 4.0.1 on 2022-01-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_syllabuses', to='courses.course')),
            ],
        ),
    ]
