# Generated by Django 4.0.1 on 2022-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_weeklysyllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysyllabus',
            name='week',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
