# Generated by Django 4.0.1 on 2022-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='instructor_name',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(default='John Davies instructor bio', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_image',
            field=models.CharField(default='https://i.imgur.com/38vwuN8.jpg', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default='this is the course overview', max_length=300),
            preserve_default=False,
        ),
    ]
