# Generated by Django 4.0.1 on 2022-01-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_instructor_course_instructor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
