# Generated by Django 4.0.1 on 2022-01-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_prerequisite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisite',
            new_name='prerequisites',
        ),
    ]
