# Generated by Django 4.0.1 on 2022-01-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_prerequisite_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysyllabus',
            name='description',
            field=models.TextField(default='my syllabus description', max_length=300),
            preserve_default=False,
        ),
    ]
